# Generated by Django 3.0.2 on 2020-02-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(max_length=80),
        ),
    ]
