# Generated by Django 3.0.2 on 2020-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten',
            name='clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
