# Generated by Django 3.0.2 on 2020-02-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20200214_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
