# Generated by Django 3.0.2 on 2020-02-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0007_auto_20200214_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField()),
                ('checkout_checkin_date', models.DateTimeField(default=None)),
                ('checkout_checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checkout_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout', to='libraryapp.Book')),
            ],
        ),
    ]
