# Generated by Django 3.0.2 on 2020-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_bookcheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='checkout_checkin_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
