# Generated by Django 3.0.2 on 2020-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_auto_20200217_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcheckout',
            old_name='checkout_checkin_date',
            new_name='checkin_date',
        ),
        migrations.AlterField(
            model_name='bookcheckout',
            name='checkout_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
