# Generated by Django 3.0.2 on 2020-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_auto_20200217_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
    ]
