# Generated by Django 3.0.2 on 2020-02-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitempriority',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
