# Generated by Django 3.0.2 on 2020-02-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200217_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookcheckout',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
    ]
