# Generated by Django 3.0.2 on 2020-02-05 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
