# Generated by Django 3.0.2 on 2020-02-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_contacts_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactsList',
        ),
    ]
