# Generated by Django 3.0.2 on 2020-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_auto_20200205_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactslist',
            name='birthday',
            field=models.DateField(),
        ),
    ]
