# Generated by Django 3.0.2 on 2020-03-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plevel', models.CharField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='TodoThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('plevel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority', to='vuetodo.Priority')),
            ],
        ),
    ]
