# Generated by Django 3.0.2 on 2020-03-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuetodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoThings',
            new_name='TodoThing',
        ),
    ]
