# Generated by Django 3.0.2 on 2020-02-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='longform',
            field=models.CharField(max_length=2000),
        ),
    ]
