# Generated by Django 3.0.2 on 2020-02-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200210_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
