# Generated by Django 3.0.2 on 2020-03-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.Priority')),
            ],
        ),
    ]
