# Generated by Django 3.0.2 on 2020-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlredirect',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
