# Generated by Django 3.0.2 on 2020-02-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('urltoshort', models.CharField(max_length=500)),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
