# Generated by Django 3.0.4 on 2020-03-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
    ]
