# Generated by Django 3.0.4 on 2020-03-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_word_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['counter', 'word']},
        ),
    ]
