# Generated by Django 3.0.4 on 2020-03-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200323_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-counter', 'word']},
        ),
    ]
