# Generated by Django 3.0.4 on 2020-03-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_remove_todoitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default=0, max_length=8),
            preserve_default=False,
        ),
    ]
