# Generated by Django 3.0.2 on 2020-02-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPSGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerchoice', models.CharField(max_length=10)),
                ('compchoice', models.CharField(max_length=10)),
                ('playername', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('humanwin', models.BooleanField()),
            ],
        ),
    ]
