input("welcome to madlibs")
anml=input("give me an animal.")
noun1=input("give me a noun.")
place=input("give me a place.")
nounpl=input("give me a plural noun.")
adj1=input("give me an adjective.")
bdypt=input("give me a bodypart.")
noun2=input("give me a noun.")
noun3=input("give me a noun.")
verbed1=input("give me a verb(past tense).")
adj2=input("give me an adjective.")
noun4=input("give me a noun.")
verbed2=input("give me a verb(past tense).")
adv=input("give me an adverb.")
print(f"Tommy the gangsta "+anml+" was walking up the street to his "+noun1+" in the "+place+". But just as he came inside he saw that all his gangsta "+nounpl+" had been replaced with "+adj1+" stuff. He was so mad that he kicked his "+bdypt+" and fell into the "+noun2+". Then, when he got out he started searching all of the "+noun1+". But after 5 hours of looking around he saw a "+noun3+" walking around with all his bling. So, Tommy stopped the fool, and "+verbed1+" all the items that the "+noun3+" had stolen from him. \"What`s your problem you "+adj2+" "+noun4+"!! If you wanna be a gangsta buy your own bling, and clothes, don`t steal mine\" Tommy "+verbed2+". And then he went home and lived "+adv+" ever after.")
