# Generated by Django 3.0.4 on 2020-03-10 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_num', models.CharField(max_length=10)),
                ('comp_last', models.CharField(max_length=20)),
                ('comp_first', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('copies', models.IntegerField()),
                ('voicing', models.CharField(max_length=20)),
                ('spec_notes', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('turn_in_date', models.DateTimeField(default=datetime.datetime(2020, 3, 10, 14, 28, 37, 863334))),
            ],
        ),
    ]
