# Generated by Django 3.0.4 on 2020-03-10 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_last', models.CharField(max_length=20, verbose_name='Last Name')),
                ('comp_first', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
            ],
        ),
        migrations.AlterField(
            model_name='composition',
            name='cat_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='Catalog No.'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='copies',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='location',
            field=models.CharField(blank=True, max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='spec_notes',
            field=models.TextField(blank=True, verbose_name='Special Notes'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='turn_in_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 14, 51, 34, 997971)),
        ),
        migrations.AlterField(
            model_name='composition',
            name='voicing',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voicing'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='comp_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositionf', to='choirapp.Composer'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='comp_last',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositionl', to='choirapp.Composer'),
        ),
    ]
