# Generated by Django 3.0.4 on 2020-03-10 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0003_auto_20200310_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='turn_in_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 15, 1, 35, 64807)),
        ),
    ]
