# Generated by Django 3.0.4 on 2020-03-10 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0004_auto_20200310_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='comp_first',
        ),
        migrations.AlterField(
            model_name='composition',
            name='comp_last',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composition', to='choirapp.Composer'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='turn_in_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 15, 8, 4, 631596)),
        ),
    ]
