# Generated by Django 3.0.4 on 2020-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0008_auto_20200311_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ['comp_last']},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['comp_last']},
        ),
    ]
