# Generated by Django 3.0.4 on 2020-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0010_auto_20200312_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
