# Generated by Django 3.0.4 on 2020-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0012_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='choristers',
            field=models.BooleanField(default=False),
        ),
    ]
