# Generated by Django 3.0.4 on 2020-03-18 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0013_composition_choristers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reh_date', models.DateField(default=datetime.datetime.today)),
                ('comp_name', models.CharField(blank=True, max_length=10, verbose_name='Composer.')),
                ('piece', models.CharField(max_length=80)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
