# Generated by Django 3.0.4 on 2020-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choirapp', '0015_auto_20200318_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehearsal',
            name='comp_name',
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='piece',
            field=models.CharField(max_length=2000),
        ),
    ]
