# Generated by Django 3.0.2 on 2020-02-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab4app', '0002_auto_20200217_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='checked',
        ),
        migrations.AddField(
            model_name='checkout',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab4app.Book'),
            preserve_default=False,
        ),
    ]
