# Generated by Django 3.0.2 on 2020-02-18 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4app', '0004_auto_20200217_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkin_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
