# Generated by Django 3.0.2 on 2020-03-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.ItemPriority'),
        ),
    ]
