# Generated by Django 3.0.2 on 2020-03-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200304_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='ListItems',
        ),
    ]
