# Generated by Django 3.0.2 on 2020-03-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200304_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItems',
            new_name='ListItem',
        ),
    ]
