# Generated by Django 3.0.2 on 2020-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_cell',
        ),
    ]
